### ISSUE TITLE
Homework Week 10

### ISSUE THREAD

**Issue by ptums** [amanakiwala/liri-node-app#1]
Hey Analben, nice job on the homework! I went through and there were a few bugs. I noticed that you were running all the functions twitterDisplay(), music(),  doAnything() whether or not the user requested it. I would remove these and take your if statement out of a function. That will allow the user to make each request. I can help you go through it line by line if you want :)

**Comment by amanakiwala** [comment]
Thank you. Would appreciate your help. I can  come early on Monday if you are available.

Thanks again,
Analben
